export default function TermsPage() {
  return (
    <div className="ot-page ot-stack">
      <h1 className="text-2xl font-semibold">Terms of Service (OtoTheory)</h1>
      
      <section className="ot-card space-y-6">
        <p className="text-sm leading-relaxed">
          By using OtoTheory (Web/iOS) provided by TH Quest, you agree to these Terms.
        </p>

        <div>
          <h2 className="text-lg font-semibold mb-2">Service Provider</h2>
          <p className="text-sm leading-relaxed">
            <strong>TH Quest</strong><br />
            Location: Kamakura, Kanagawa, Japan<br />
            Contact: <a href="mailto:support@ototheory.com" className="underline">support@ototheory.com</a>
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Eligibility</h2>
          <p className="text-sm leading-relaxed">
            You must be 13 years of age or older to use this service. Sign in with Apple is required for iOS app users.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Subscription</h2>
          <ul className="list-disc pl-5 text-sm leading-relaxed space-y-1">
            <li><strong>Price</strong>: Pro subscription at ¥490/month (prices may vary by region)</li>
            <li><strong>Auto-renewing</strong>: Subscription automatically renews unless canceled at least 24 hours before the end of the current period</li>
            <li><strong>Free Trial</strong>: 7-day free trial available for new subscribers</li>
            <li><strong>Cancellation</strong>: Cancel anytime via Apple ID &gt; Subscriptions &gt; OtoTheory</li>
            <li><strong>Refunds</strong>: Refund requests are subject to Apple&apos;s refund policy</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Output Rights</h2>
          <p className="text-sm leading-relaxed">
            PNG images and MIDI files exported from OtoTheory belong to you, the user. However, you are responsible for ensuring that any third-party content used complies with applicable copyright and licensing laws.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Prohibited Conduct</h2>
          <p className="text-sm leading-relaxed mb-2">You agree not to:</p>
          <ul className="list-disc pl-5 text-sm leading-relaxed space-y-1">
            <li>Reverse engineer, decompile, or disassemble the software</li>
            <li>Attempt unauthorized access to our systems or other users&apos; accounts</li>
            <li>Engage in unlawful, abusive, or harmful behavior</li>
            <li>Infringe on the intellectual property rights of others</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Disclaimer of Warranties</h2>
          <p className="text-sm leading-relaxed">
            OtoTheory is provided &quot;as is&quot; without warranties of any kind, express or implied. We do not guarantee that the service will be uninterrupted, error-free, or meet your specific requirements. Commercial use of outputs generated by OtoTheory is at your own risk and responsibility.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Limitation of Liability</h2>
          <p className="text-sm leading-relaxed">
            To the maximum extent permitted by law, TH Quest shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of OtoTheory.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Service Changes and Termination</h2>
          <p className="text-sm leading-relaxed">
            We may add, modify, suspend, or discontinue features at any time. Material changes will be announced on this site. We reserve the right to terminate accounts that violate these Terms.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Account Deletion</h2>
          <p className="text-sm leading-relaxed">
            You may delete your account at any time via Settings &gt; Delete Account in the app, or by emailing us at{' '}
            <a href="mailto:support@ototheory.com" className="underline">support@ototheory.com</a>.
            All cloud-saved data will be purged within 30 days of deletion.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Governing Law and Jurisdiction</h2>
          <p className="text-sm leading-relaxed">
            These Terms are governed by the laws of Japan. Any disputes arising from these Terms or your use of OtoTheory shall be subject to the exclusive jurisdiction of the Kanagawa District Court.
          </p>
        </div>

        <div>
          <h2 className="text-lg font-semibold mb-2">Changes to Terms</h2>
          <p className="text-sm leading-relaxed">
            We may update these Terms from time to time. Material changes will be announced on this page. Your continued use of OtoTheory after changes are posted constitutes your acceptance of the updated Terms.
          </p>
        </div>

        <p className="text-xs opacity-70 mt-6 pt-4 border-t border-black/10 dark:border-white/10">
          <strong>(Last updated: 2025‑10‑03)</strong>
        </p>
      </section>
    </div>
  );
}

