name: Deploy to Vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ototheory-web/package-lock.json
        
    - name: Install dependencies
      run: |
        cd ototheory-web
        npm --version
        node --version
        ls -la
        cat package.json
        npm ci --verbose
        
    - name: Build
      run: |
        cd ototheory-web
        npm run build
        
    - name: Install Vercel CLI
      run: |
        npm install -g vercel@latest
        
    - name: Deploy to Vercel
      run: |
        cd ototheory-web
        vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_ORG_ID }} --prod --yes
      env:
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}