name: Drive Sync

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/SSOT/OtoTheory_v3.0_SSOT.md'
      - 'docs/SSOT/OtoTheory_Roadmap_Milestones.md'
      - 'reports/**'
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install googleapis@131

      - name: Run drive sync
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}
          GDRIVE_FOLDER_SSOT: ${{ secrets.GDRIVE_FOLDER_SSOT }}
          GDRIVE_FOLDER_REPORTS: ${{ secrets.GDRIVE_FOLDER_REPORTS }}
        run: node scripts/drive_sync.mjs

